# config.py

TELEGRAM_API_TOKEN = 'YOUR_TELEGRAM_BOT_API_TOKEN'
OPENAI_API_KEY = 'org-9RoFPyxUkWFS0RSk8tp24zAf'
REMOVE_BG_API_KEY = 'BsmMwthnjAsbxNVD84anrGDQ'
VOICE_CHANGER_API_URL = 'IHje5imgq693AJJJEIyybwtt'  # Replace with actual URL
