# config.py

TELEGRAM_API_TOKEN = 'YOUR_TELEGRAM_BOT_API_TOKEN'
OPENAI_API_KEY = 'YOUR_OPENAI_API_KEY'
REMOVE_BG_API_KEY = 'YOUR_REMOVE_BG_API_KEY'
VOICE_CHANGER_API_URL = 'YOUR_VOICE_CHANGER_API_URL'  # Replace with actual URL
